<?xml version='1.0' encoding='utf-8'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="panda">
  <!-- safety_distance: Minimum safety distance in [m] by which the collision volumes are expanded and which is enforced during robot motions -->
  <!-- arm_id: Namespace of the panda arm. Serves to differentiate between arms in case of multiple instances. -->
  <xacro:macro name="panda_arm" params="arm_id:='panda' description_pkg:='franka_coppelia_hw' connected_to:='' xyz:='0 0 0' rpy:='0 0 0' safety_distance:=0">
    <xacro:unless value="${not connected_to}">
      <joint name="${arm_id}_joint_${connected_to}" type="fixed">
        <parent link="${connected_to}"/>
        <child link="${arm_id}_link0"/>
        <origin rpy="${rpy}" xyz="${xyz}"/>
      </joint>
    </xacro:unless>
    <link name="${arm_id}_link0">
      <visual>
        <geometry>
          <mesh filename="package://${description_pkg}/meshes/visual/link0.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="-0.075 0 0.06" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder radius="${0.06+safety_distance}" length="0.03" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="-0.06 0 0.06" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="-0.09 0 0.06" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
    </link>
    <link name="${arm_id}_link1">
      <visual>
        <geometry>
          <mesh filename="package://${description_pkg}/meshes/visual/link1.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 -0.1915" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${0.06+safety_distance}" length="0.2830" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -0.333" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -0.05" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
    </link>
    <joint name="${arm_id}_joint1" type="revolute">
      <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-2.8973" soft_upper_limit="2.8973"/>
      <origin rpy="0 0 0" xyz="0 0 0.333"/>
      <parent link="${arm_id}_link0"/>
      <child link="${arm_id}_link1"/>
      <axis xyz="0 0 1"/>
      <limit effort="87" lower="-2.8973" upper="2.8973" velocity="2.1750"/>
    </joint>
    <link name="${arm_id}_link2">
      <inertial>
            <origin xyz="0.000027 -0.031145 0.262891" rpy="-3.141593 3.141593 -3.141593" />
            <inertia ixx="0.23965416449794" iyz="0.046543293301451" ixz="1.3128335716866e-05" ixy="1.8036869099987e-05" izz="0.096472146190744" iyy="0.20795149177852" />
            <mass value="4.9706840515137" />
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://${description_pkg}/meshes/visual/link2.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${0.06+safety_distance}" length="0.12" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -0.06" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 0.06" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
    </link>
    <joint name="${arm_id}_joint2" type="revolute">
      <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-1.7628" soft_upper_limit="1.7628"/>
      <origin rpy="${-pi/2} 0 0" xyz="0 0 0"/>
      <parent link="${arm_id}_link1"/>
      <child link="${arm_id}_link2"/>
      <axis xyz="0 0 1"/>
      <limit effort="87" lower="-1.7628" upper="1.7628" velocity="2.1750"/>
    </joint>
    <link name="${arm_id}_link3">
     <inertial>
            <origin xyz="0.000012 -0.070031 0.031073" rpy="-1.570796 3.141593 -3.141593" />
            <inertia ixx="0.021097005907894" iyz="0.0040788476591549" ixz="-9.6899135443004e-07" ixy="4.6746993616892e-06" izz="0.0083947222563338" iyy="0.018332235221749" />
            <mass value="0.64692598581314" />
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://${description_pkg}/meshes/visual/link3.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 -0.145" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${0.06+safety_distance}" length="0.15" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -0.22" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -0.07" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
    </link>
    <joint name="${arm_id}_joint3" type="revolute">
      <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-2.8973" soft_upper_limit="2.8973"/>
      <origin rpy="${pi/2} 0 0" xyz="0 -0.316 0"/>
      <parent link="${arm_id}_link2"/>
      <child link="${arm_id}_link3"/>
      <axis xyz="0 0 1"/>
      <limit effort="87" lower="-2.8973" upper="2.8973" velocity="2.1750"/>
    </joint>
    <link name="${arm_id}_link4">
      <inertial>
            <origin xyz="0.044418 0.025018 0.276461" rpy="-3.141592 3.141593 3.141593" />
            <inertia ixx="0.037043165158734" iyz="-0.0066345366154784" ixz="-0.012283585683442" ixy="-0.0071662360347711" izz="0.037313700213202" iyy="0.044600332011806" />
            <mass value="3.2286040782928" />
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://${description_pkg}/meshes/visual/link4.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${0.06+safety_distance}" length="0.12" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 0.06" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -0.06" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
    </link>
    <joint name="${arm_id}_joint4" type="revolute">
      <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-3.0718" soft_upper_limit="-0.0698"/>
      <origin rpy="${pi/2} 0 0" xyz="0.0825 0 0"/>
      <parent link="${arm_id}_link3"/>
      <child link="${arm_id}_link4"/>
      <axis xyz="0 0 1"/>
      <limit effort="87" lower="-3.0718" upper="-0.0698" velocity="2.1750"/>
    </joint>
    <link name="${arm_id}_link5">
      <inertial>
            <origin xyz="-0.036035 0.041072 0.024354" rpy="1.570796 3.141593 3.071779" />
            <inertia ixx="0.04844892193307" iyz="-0.0086501440884625" ixz="0.016026606898086" ixy="0.0091601974989418" izz="0.047764716548773" iyy="0.05816570900911" />
            <mass value="3.5878949165344" />
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://${description_pkg}/meshes/visual/link5.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 -0.26" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${0.06+safety_distance}" length="0.1" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -0.31" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -0.21" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0.08 -0.13" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${0.025+safety_distance}" length="0.14" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0.08 -0.06" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.025+safety_distance}" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0.08 -0.20" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.025+safety_distance}" />
        </geometry>
      </collision>

    </link>
    <joint name="${arm_id}_joint5" type="revolute">
      <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-2.8973" soft_upper_limit="2.8973"/>
      <origin rpy="${-pi/2} 0 0" xyz="-0.0825 0.384 0"/>
      <parent link="${arm_id}_link4"/>
      <child link="${arm_id}_link5"/>
      <axis xyz="0 0 1"/>
      <limit effort="12" lower="-2.8973" upper="2.8973" velocity="2.6100"/>
    </joint>
    <link name="${arm_id}_link6">
      <inertial>
          <origin xyz="0.000101 0.038651 -0.110916" rpy="3.141593 3.141592 3.141592" />
          <inertia ixx="0.03988537400492" iyz="-0.0078141474579038" ixz="-2.672442414716e-05" ixy="6.5734913571839e-07" izz="0.010430599214868" iyy="0.036230106859883" />
          <mass value="1.2259459495544" />
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://${description_pkg}/meshes/visual/link6.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 -0.03" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${0.05+safety_distance}" length="0.08" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 0.01" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.05+safety_distance}" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -0.07" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.05+safety_distance}" />
        </geometry>
      </collision>
    </link>
    <joint name="${arm_id}_joint6" type="revolute">
      <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-0.0175" soft_upper_limit="3.7525"/>
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
      <parent link="${arm_id}_link5"/>
      <child link="${arm_id}_link6"/>
      <axis xyz="0 0 1"/>
      <limit effort="12" lower="-0.0175" upper="3.7525" velocity="2.6100"/>
    </joint>
    <link name="${arm_id}_link7">
      <inertial>
          <origin xyz="0.050819 0.005558 0.005395" rpy="1.570796 3.141593 3.141593" />
          <inertia ixx="0.0046587251169735" iyz="-6.1476550160376e-05" ixz="-0.00030740988325929" ixy="-0.00057744119112155" izz="0.0070729035771789" iyy="0.008643924526682" />
          <mass value="1.6665550470352" />
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://${description_pkg}/meshes/visual/link7.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0.01" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${0.04+safety_distance}" length="0.14" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 0.08" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.04+safety_distance}"  />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -0.06" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.04+safety_distance}"  />
        </geometry>
      </collision>
    </link>
    <joint name="${arm_id}_joint7" type="revolute">
      <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-2.8973" soft_upper_limit="2.8973"/>
      <origin rpy="${pi/2} 0 0" xyz="0.088 0 0"/>
      <parent link="${arm_id}_link6"/>
      <child link="${arm_id}_link7"/>
      <axis xyz="0 0 1"/>
      <limit effort="12" lower="-2.8973" upper="2.8973" velocity="2.6100"/>
    </joint>
    <link name="${arm_id}_link8">
      <inertial>
            <origin xyz="-0.000077 -0.000876 0.078618" rpy="-0.000000 3.141593 -3.141592" />
            <inertia ixx="0.0088670116631003" iyz="-9.1760218741593e-08" ixz="7.00227187462e-07" ixy="7.6321250755392e-11" izz="0.01180331651387" iyy="0.0088670122123097" />
            <mass value="0.73552197217941" />
      </inertial>
      <collision>
        <origin xyz="0.0424 0.0424 -0.0250" rpy="${pi} ${pi/2} ${pi/2}"/>
        <geometry>
          <cylinder radius="${0.03+safety_distance}"  length="0.01" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0.0424 0.0424 -0.02" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.03+safety_distance}"  />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0.0424 0.0424 -0.03" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.03+safety_distance}"  />
        </geometry>
      </collision>
    </link>
    <joint name="${arm_id}_joint8" type="fixed">
      <origin rpy="0 0 0" xyz="0 0 0.107"/>
      <parent link="${arm_id}_link7"/>
      <child link="${arm_id}_link8"/>
    </joint>
  </xacro:macro>
</robot>
