name: Jazzy CI

on:
  push:
  pull_request:

jobs:
  industrial_ci:
    strategy:
      fail-fast: false
      matrix:
        env:
          - {ROS_DISTRO: jazzy, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}